// <auto-generated />
using System;
using Infraestructure.Pagos.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Pagos.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20230712051246_DecimalMonto")]
    partial class DecimalMonto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infraestructure.Pagos.EF.ReadModel.PagoReadModel", b =>
                {
                    b.Property<Guid>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("idPago");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyectoId");

                    b.HasKey("IdPago");

                    b.ToTable("pago", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
